### ISSUE TITLE
CMakeFiles/Makefile2:5154: recipe for target '........frcobot_gripper.dir/all' failed

### ISSUE THREAD

**Issue by Stark-Bear** [FAIR-INNOVATION/frcobot_ros#1]
when I try  "catkin_make" ,it show me this error. Not only this error , just see as below:

/usr/bin/ld: cannot find -lxmlrpcpp
collect2: error: ld returned 1 exit status
frcobot_ros/frcobot_gripper/CMakeFiles/frcobot_gripper.dir/build.make:174: recipe for target '/home/xxp/docs/melodic/frrobot_ws/devel/lib/libfrcobot_gripper.so' failed
make[2]: *** [/home/xxp/docs/melodic/frrobot_ws/devel/lib/libfrcobot_gripper.so] Error 1
CMakeFiles/Makefile2:5154: recipe for target 'frcobot_ros/frcobot_gripper/CMakeFiles/frcobot_gripper.dir/all' failed
make[1]: *** [frcobot_ros/frcobot_gripper/CMakeFiles/frcobot_gripper.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by FAIR-INNOVATION** [comment]
Hi! 
Try this:
`sudo apt-get install libxmlrpcpp-dev`
and it should compile successfully.

**Comment by Stark-Bear** [comment]
> Hi! Try this: `sudo apt-get install libxmlrpcpp-dev` and it should compile successfully.

Thanks for reply. I had found the solution in the readme.md , it notes the solution just as your reply .
